### ISSUE TITLE
module 'persian' has no attribute 'convert_fa_numbers'

### ISSUE THREAD

**Issue by msadeghyan1996** [rezakamalifard/Persian#15]
Hi. first tanx for this package. i would use it but return this error for me: 
module 'persian' has no attribute 'convert_fa_numbers'
installed version : 0.0.4

**Comment by psamim** [comment]
That is because the pip version is not updated https://github.com/rezakamalifard/Persian/issues/13

**Comment by psamim** [comment]
Install directly from github `pip install git+https://github.com/rezakamalifard/Persian`

**Comment by rezakamalifard** [comment]
I've updated the pip module to the latest version
