### ISSUE TITLE
enToPersianChar needs an update

### ISSUE THREAD

**Issue by MHM5000** [rezakamalifard/Persian#7]
1. There are several Keyboard Layouts.
2. Chars like آ, ٔ, ،, etc. are not available in this function

**Comment by itmard** [comment]
Good idea can you provide the mapping dictionary. I can update it. @MHM5000

**Comment by rezakamalifard** [comment]
@Abbasd67 Please send PR here

**Comment by rezakamalifard** [comment]
minimum version of python requirement for this package is 3.6
